package(default_visibility = ["//visibility:private"])

cc_library(
    name = "aux",
    hdrs = [
        "min_max_helpers.h",
        "min_max_tree_heap.h",
        "min_max_vector_heap.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//include/phtree/common",
    ],
)
