package(default_visibility = ["//visibility:private"])

cc_library(
    name = "v20",
    srcs = [
    ],
    hdrs = [
        "debug_helper_v20.h",
        "entry.h",
        "for_each.h",
        "for_each_hc.h",
        "iterator_base.h",
        "iterator_full.h",
        "iterator_hc.h",
        "iterator_knn_hs.h",
        "iterator_lower_bound.h",
        "iterator_with_key.h",
        "iterator_with_parent.h",
        "node.h",
        "phtree_v20.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//include/phtree/common",
    ],
)
