name: Upload CodeCov Report
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    name: Build, Test , Upload Code Coverage Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
        id: checkout_code
        #- name: Setup MSBuild and add to PATH
        #  uses: microsoft/setup-msbuild@v1.0.2
        #  id: setup_msbuild
        #- name: Run MSBuild
        #  id: run_msbuild
        #  run: msbuild /p:Configuration=Debug /p:Platform=x86 HelloCovDemo.sln
        #- name: Setup VSTest and add to PATH
        #  uses: darenm/Setup-VSTest@v1
        #  id: setup_vstest

      - uses: ilammy/msvc-dev-cmd@v1

      #- name: Create Build Environment
      #  run: cmake -E make_directory ${{github.workspace}}\out

      #- name: Configure CMake
      #  working-directory: ${{github.workspace}}\out
      #  run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -S ${{github.workspace}} -B ${{github.workspace}}\out -DPHTREE_BUILD_EXAMPLES=ON -DPHTREE_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build
        working-directory: ${{github.workspace}}\out
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        #run: cmake --build . --config ${env:BUILD_TYPE}
        run: cmake -G "Visual Studio 16 2019"

      #- name: Test
      #  working-directory: ${{github.workspace}}\out
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #  run: ctest -C ${env:BUILD_TYPE}

      - name: Setup OpenCppCoverage and add to PATh
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --sources HelloCov --export_type cobertura:HelloCov.xml -- "vstest.console.exe" Debug\HelloTest.dll
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./HelloCov.xml
          fail_ci_if_error: true
          functionalities: fix

          # https://github.com/codecov/codecov-action#usage
          # https://app.codecov.io/gh/tzaeschke/phtree-cpp/new